### PR TITLE
feat: Add execute command to handle Execute code lens

### PR DESCRIPTION
**Pull request by phated**
# Description

## Problem\*

Ref https://github.com/noir-lang/noir/pull/2330 

## Summary\*

This adds a `nargo.execute` command that will be triggered via the `> Execute` code lens.

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by TomAFrench** [comment]
I'm building this with `npm run package` (and then selecting "Install Extension VSIX" in the sidebar) and running it with Nargo built from your PR. I'm not getting any display and a "Unable to locate any nargo binary. Did you install it?" error.

Should I be doing something different to test this?

**Comment by phated** [comment]
So the published extension doesn't work for you either? I use a custom absolute path to my nargo binary since I iterate on the features so I've not experienced this. Seems entirely unrelated to this PR

**Comment by TomAFrench** [comment]
Yeah, I really doubt it has anything to do with this PR. Just trying to get to a state where I can meaningfully test it.

**Comment by TomAFrench** [comment]
I don't get any errors on the published extension (v0.0.3) but nothing past syntax highlighting either. I've switched back to the locally installed extension and don't get the error anymore but no output either. Adding an explicit path causes no change.

**Comment by TomAFrench** [comment]
Ah ha! I've managed to get signs of life.

**Review by TomAFrench — APPROVED** [review]

**Pull request merged**
