### PR TITLE
feat: add opcodes profile information

### PR DESCRIPTION
**Pull request by kobyhallx**
Adds Command (with codelens `Profile` and key binding `shift+alt+ctrl+n p` to invoke profile command in LSP and display results as line decoration at the end, eg. `// 15 ACIR opcodes`. More detailed information is available on hover of individual code fragment (span).

image

Part of 
feat: Expose Profile information in vscode https://github.com/noir-lang/noir/issues/3501

### CODE REVIEW

**Comment by kobyhallx** [comment]
Needs https://github.com/noir-lang/noir/pull/3496

**Comment by signorecello** [comment]
this is great, thanks @kobyhallx

**Review by signorecello — APPROVED** [review]

**Comment by TomAFrench** [comment]
I'm not seeing any line decorations in vscode. It's instead throwing an error that `window.activeTextEditor` is undefined.

**Comment by kobyhallx** [comment]
> Edit: managed to fix this. There's not very good feedback in the case where the profiling codelens fails.

Are you going to bring this fix back?

**Pull request merged**
